### ISSUE TITLE
needs update for string.data changes

### ISSUE THREAD

**Issue by stevengj** [Keno/TerminalUI.jl#13]
After JuliaLang/julia#19449, soon to be merged for Julia 0.6, you will no longer be able to access the raw bytes of a string via `string.data`; instead, do `Vector{UInt8}(string)`.  For example, this affects:

https://github.com/Keno/TerminalUI.jl/blob/479a844fb50a4c8171b1cf5b6e758d923ce3f3c0/test/regressions.jl#L62

**Comment by Keno** [comment]
This was done.
